# Site settings
name: southeast-ideas
email: wangcc0106@gmail.com #luoyan35714@126.com
author: Michael Wang #Freud Kang
url: http://www.southeast-ideas.com
resume_site: #http://www.hifreud.com/Resume.io/
github: https://github.com/WangChengCheng/
baseurl: ""
description: Actually, less is more!
meta_description: 东南思想 #康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: WangChengCheng
highlighter: Pygments

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : changyan
    # duoshuo:
    #     short_name : luoyan35714
    
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
